### ISSUE TITLE
Can boost::flyweight support boost::compute and nlohmann::json?

### ISSUE THREAD

**Issue by akeyliu** [boostorg/flyweight#8]
Hello, and really thanks for your support for boost::flyweight.
1. I'm now using boost::compute for GPU programming, and If boost::flyweight support boost:compute?
2. I'm now using nlohmann::json for JSON process, and can boost::flyweight support nlohmann::json?
    i.e.   
     boost::flyweight\<int\> aa = 123;
     nlohmann::json j = aa;

Thanks.
Kevin Liu

**Comment by joaquintides** [comment]
1: I'm not sure I understand your question: certainly you can't pass a flyweight object to OpenCL, the only admissible types are scalars and the like.

2: A JSON object can only hold numbers, strings, booleans, arrays, nulls and key-value objects. So you can't store a flyweight object directly, though you can write:
```
 boost::flyweight<int> aa = 123;
 nlohmann::json j = aa.get(); // get the underlying int
```

Is this what you had in mind?
